version: '3'

services:
  web:
    build: ./
    ports:
      - "5000:5000"
    #depends_on:
     # - mongo
    #environment:
     # MONGO_URI: mongodb://mongo:27017/inventoryDB # Change 'mydatabase' to the name of your database
    networks:
      - backend

  mongo:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - ./data:/data/db # Optional: persist data to a local directory
    networks:
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
