apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
spec:
  storageClassName: ""
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: ""
  volumeName: mongo-volume
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1G