apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
      nodePort: 30002
  type: LoadBalancer
  externalIPs:
  - 192.168.64.2
  