# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with unittest
      run: |
        python test_app.py
    - name: build docker image
      run : |
          docker build -t myapp:latest .
    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
    # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
    # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
         # Specifies whether the given registry is ECR (auto, true or false)
        ecr:  auto
    # Log out from the Docker registry at the end of a job
        logout: true
    - name: Push Docker image to Docker Hub
      run: |
          docker push azizjouini/myapp:latest
   
